Repository UBC-MDS/DSCI-532_gr202_dashboard, pull requests merged in 2019-12, with the labels that each got.

#59 Fix point 1,2,3 on issue #54
  app.py
Labels: enhancement

#60 fix issue #54 point 4, add the data source on footer
  app.py
Labels: enhancement

#62 Modularization, Cleaned up code, Added Snippets
  .vscode/settings.json
  helpers.py
  reflection.md
Labels: enhancement

#61 fixed issue #54
  app.py
Labels: enhancement

#64 fixed bug relating to missing functions in helper
  app.py
  helpers.py
Labels: bug

#65 [ENH] updated trend plot function to show full year in axis
  helpers.py
Labels: enhancement

#67 [DOC] Fix minor typos on reflection file
  reflection.md
Labels: documentation

#68 change headers on reflection
  reflection.md
Labels: documentation

#69 [DOC] delete the milestone 2 Heroku link in readme
  README.md
Labels: documentation

#71 merge the changes from master to milestone 3 branch
  README.md
  app.py
  reflection.md
Labels: enhancement

#74 update milestone 3 with master
  reflection.md
Labels: documentation
